### PR TITLE
fix npc shop prices

### PR DESCRIPTION
**Pull request by TreesOnTop**
Items that by default are bought in multiples had incorrect prices, for example buying 10 flint costs 600 coins when it should be costing 60

### CODE REVIEW

**Comment by ItzKatze** [comment]
hey there, you basically removed every item that was bought in a multiple and made it single which should not be done. Instead of that we need to fix how the price is calculated

**Comment by TreesOnTop** [comment]
thats not what I did but its fixed now so its fine

**Comment by TreesOnTop** [comment]
mostly the only item I changed the amount of was arrows because they aren't bought in multiples on hypixel

**Comment by ItzKatze** [comment]
oh true i misslooked that

**Pull request closed without merging**
